// src/engine/TrackEnvironmentEngine.js
// RW5.2D2 — dynamic air/track temperature and visibility/spray model.
//
// D1 owns the physical track surface (water/rubber/grip). D2 consumes that
// surface and evolves the surrounding environment. This deliberately stays
// deterministic: the weather state is already generated by WeekendWeather.

const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)||0));
const num=(v,fb=0)=>{const n=Number(v);return Number.isFinite(n)?n:fb;};
const upper=(v)=>String(v??"SUNNY").toUpperCase();

const SOLAR_LOAD=Object.freeze({
  SUNNY:1,
  CLOUDY:0.46,
  WINDY:0.54,
  DRYING:0.62,
  DRIZZLE_DRYING:0.48,
  WETTING:0.28,
  LIGHT_RAIN:0.16,
  HEAVY_RAIN:0.06,
  STORM:0.02,
});

const AIR_OFFSET_C=Object.freeze({
  SUNNY:1.0,
  CLOUDY:0,
  WINDY:-0.4,
  DRYING:-0.6,
  DRIZZLE_DRYING:-0.8,
  WETTING:-1.2,
  LIGHT_RAIN:-1.8,
  HEAVY_RAIN:-2.8,
  STORM:-3.6,
});

function windFactor(profile){
  const p=String(profile??"medium").toLowerCase();
  if(p==="high"||p==="strong")return 1.15;
  if(p==="low"||p==="calm")return 0.90;
  return 1;
}

function solarCycle(progress){
  const p=clamp(progress,0,1);
  // A race/session warms toward the middle before easing slightly later.
  return 0.90+Math.sin(Math.PI*p)*0.15;
}

function targetTrackTemp({airTempC,state,wetness,rainIntensity,sessionProgress}={}){
  const weatherState=upper(state);
  const air=num(airTempC,22);
  const wet=clamp(wetness,0,1);
  const intensity=clamp(rainIntensity,0,1);
  const solar=(SOLAR_LOAD[weatherState]??0.45)*solarCycle(sessionProgress);
  const solarGain=5.5+solar*12.5;
  const wetCooling=wet*7.5;
  const rainCooling=intensity*4.5;
  return clamp(air+solarGain-wetCooling-rainCooling,air-1.5,air+21);
}

export function sprayIndexForConditions({
  wetness=0,
  rainIntensity=0,
  carsOnTrack=20,
  windProfile="medium",
}={}){
  const wet=clamp(wetness,0,1);
  const intensity=clamp(rainIntensity,0,1);
  const traffic=clamp(num(carsOnTrack,20)/20,0,1.6);
  if(wet<0.015&&intensity<0.02)return 0;
  const raw=wet*(0.30+0.62*traffic)*(0.72+intensity*0.45);
  // Wind disperses the spray cloud slightly faster; calm air lets it linger.
  return clamp(raw/windFactor(windProfile),0,1);
}

export function visibilityIndexForConditions({
  state="SUNNY",
  wetness=0,
  rainIntensity=0,
  carsOnTrack=20,
  windProfile="medium",
}={}){
  const intensity=clamp(rainIntensity,0,1);
  const spray=sprayIndexForConditions({wetness,rainIntensity,carsOnTrack,windProfile});
  const storm=upper(state)==="STORM"?0.08:0;
  const windRelief=Math.max(0,windFactor(windProfile)-1)*0.10;
  const visibility=clamp(1-intensity*0.30-spray*0.50-storm+windRelief,0.22,1);
  return Number((visibility*100).toFixed(1));
}

export function visibilityBand(value){
  const n=clamp(num(value,100),0,100);
  if(n>=90)return "CLEAR";
  if(n>=72)return "REDUCED";
  if(n>=52)return "POOR";
  return "VERY_POOR";
}

export function sprayBand(value){
  const n=clamp(num(value,0),0,1);
  if(n<0.08)return "NONE";
  if(n<0.30)return "LIGHT";
  if(n<0.58)return "MODERATE";
  if(n<0.80)return "HEAVY";
  return "EXTREME";
}

export function initialiseTrackEnvironment({
  state="SUNNY",
  baseAirTempC=22,
  airTempC=null,
  trackTempC=null,
  wetness=0,
  rainIntensity=0,
  carsOnTrack=20,
  windProfile="medium",
  sessionProgress=0,
}={}){
  const weatherState=upper(state);
  const hasAirTemp=airTempC!==null&&airTempC!==undefined&&Number.isFinite(Number(airTempC));
  const air=hasAirTemp
    ?Number(airTempC)
    :num(baseAirTempC,22)+(AIR_OFFSET_C[weatherState]??0);
  const target=targetTrackTemp({
    airTempC:air,
    state:weatherState,
    wetness,
    rainIntensity,
    sessionProgress,
  });
  const hasTrackTemp=trackTempC!==null&&trackTempC!==undefined&&Number.isFinite(Number(trackTempC));
  const track=hasTrackTemp?Number(trackTempC):target;
  const spray=sprayIndexForConditions({wetness,rainIntensity,carsOnTrack,windProfile});
  const visibility=visibilityIndexForConditions({state:weatherState,wetness,rainIntensity,carsOnTrack,windProfile});
  return {
    state:weatherState,
    air_temp_c:Number(air.toFixed(1)),
    track_temp_c:Number(track.toFixed(1)),
    spray_index:Number(spray.toFixed(3)),
    spray_band:sprayBand(spray),
    visibility_index:visibility,
    visibility_band:visibilityBand(visibility),
  };
}

export function evolveTrackEnvironment(previous,{
  state="SUNNY",
  baseAirTempC=22,
  wetness=0,
  rainIntensity=0,
  carsOnTrack=20,
  windProfile="medium",
  sessionProgress=0,
  lapFraction=1,
}={}){
  const prev=previous||initialiseTrackEnvironment({
    state,baseAirTempC,wetness,rainIntensity,carsOnTrack,windProfile,sessionProgress,
  });
  const weatherState=upper(state);
  const fraction=clamp(lapFraction,0.05,4);
  const intensity=clamp(rainIntensity,0,1);
  const wet=clamp(wetness,0,1);
  const progress=clamp(sessionProgress,0,1);

  const ambientTarget=num(baseAirTempC,22)
    +(AIR_OFFSET_C[weatherState]??0)
    +Math.sin(Math.PI*progress)*0.7;
  const airResponse=clamp((0.055+intensity*0.035)*fraction,0.02,0.30);
  const air=num(prev.air_temp_c,ambientTarget)+(ambientTarget-num(prev.air_temp_c,ambientTarget))*airResponse;

  const trackTarget=targetTrackTemp({
    airTempC:air,
    state:weatherState,
    wetness:wet,
    rainIntensity:intensity,
    sessionProgress:progress,
  });
  // Wet/raining asphalt changes temperature more quickly than a dry surface
  // because evaporative/rain cooling is strong.
  const trackResponse=clamp((0.12+wet*0.08+intensity*0.10)*fraction,0.05,0.42);
  const track=num(prev.track_temp_c,trackTarget)+(trackTarget-num(prev.track_temp_c,trackTarget))*trackResponse;

  const spray=sprayIndexForConditions({
    wetness:wet,
    rainIntensity:intensity,
    carsOnTrack,
    windProfile,
  });
  const visibility=visibilityIndexForConditions({
    state:weatherState,
    wetness:wet,
    rainIntensity:intensity,
    carsOnTrack,
    windProfile,
  });

  return {
    state:weatherState,
    air_temp_c:Number(air.toFixed(1)),
    track_temp_c:Number(track.toFixed(1)),
    spray_index:Number(spray.toFixed(3)),
    spray_band:sprayBand(spray),
    visibility_index:visibility,
    visibility_band:visibilityBand(visibility),
  };
}

export function evolveSessionEnvironment(previous,{
  state="SUNNY",
  kind="practice",
  baseAirTempC=22,
  wetnessStart=0,
  wetnessEnd=0,
  rainIntensity=0,
  carsOnTrack=20,
  windProfile="medium",
  gapDays=0,
}={}){
  const fresh=initialiseTrackEnvironment({
    state,
    baseAirTempC,
    wetness:wetnessStart,
    rainIntensity,
    carsOnTrack,
    windProfile,
    sessionProgress:0,
  });

  let start=fresh;
  if(previous&&Number(gapDays)<=0){
    // Same-day sessions keep meaningful thermal inertia.
    start={
      ...fresh,
      air_temp_c:Number((num(previous.air_temp_c,fresh.air_temp_c)*0.42+fresh.air_temp_c*0.58).toFixed(1)),
      track_temp_c:Number((num(previous.track_temp_c,fresh.track_temp_c)*0.58+fresh.track_temp_c*0.42).toFixed(1)),
    };
  }else if(previous&&Number(gapDays)>0){
    // Overnight the track largely resets toward the new day's conditions.
    start={
      ...fresh,
      track_temp_c:Number((num(previous.track_temp_c,fresh.track_temp_c)*0.12+fresh.track_temp_c*0.88).toFixed(1)),
    };
  }

  const steps=kind==="practice"?18:kind==="qualifying"?12:kind==="race"?24:10;
  let end=start;
  for(let i=0;i<steps;i+=1){
    const progress=(i+1)/steps;
    const wetness=num(wetnessStart)+(num(wetnessEnd)-num(wetnessStart))*progress;
    end=evolveTrackEnvironment(end,{
      state,
      baseAirTempC,
      wetness,
      rainIntensity,
      carsOnTrack,
      windProfile,
      sessionProgress:progress,
      lapFraction:1,
    });
  }

  return {
    start_air_temp_c:Number(start.air_temp_c.toFixed(1)),
    end_air_temp_c:Number(end.air_temp_c.toFixed(1)),
    start_track_temp_c:Number(start.track_temp_c.toFixed(1)),
    end_track_temp_c:Number(end.track_temp_c.toFixed(1)),
    start_visibility_index:Number(start.visibility_index.toFixed(1)),
    end_visibility_index:Number(end.visibility_index.toFixed(1)),
    start_spray_index:Number(start.spray_index.toFixed(3)),
    end_spray_index:Number(end.spray_index.toFixed(3)),
    visibility_band:end.visibility_band,
    spray_band:end.spray_band,
    // Backwards-compatible aliases for consumers that expect one value.
    air_temp_c:Number(start.air_temp_c.toFixed(1)),
    track_temp_c:Number(start.track_temp_c.toFixed(1)),
    visibility_index:Number(start.visibility_index.toFixed(1)),
    spray_index:Number(start.spray_index.toFixed(3)),
  };
}
